kind: pipeline
type: docker
name: allScreenshots

steps:
  - name: runAllScreenshots
    image: nextcloudci/android8:android-61
    privileged: true
    environment:
      GIT_USERNAME:
        from_secret: GIT_USERNAME
      GIT_TOKEN:
        from_secret: GIT_TOKEN
      LOG_USERNAME:
        from_secret: LOG_USERNAME
      LOG_PASSWORD:
        from_secret: LOG_PASSWORD
    commands:
      - emulator -avd android -no-snapshot -gpu swiftshader_indirect -no-window -no-audio -skin 500x833 &
      - sed -i s'#<bool name="is_beta">false</bool>#<bool name="is_beta">true</bool>#'g src/main/res/values/setup.xml
      - sed -i s'#showOnlyFailingTestsInReports = ciBuild#showOnlyFailingTestsInReports = false#' build.gradle
      - scripts/wait_for_emulator.sh
      - scripts/runAllScreenshotCombinations noCI false
      - mkdir -p build/screenshotSummary/images
      - scripts/generateScreenshotOverview.sh > build/screenshotSummary/summary.html
      - scripts/uploadScreenshotSummary.sh $LOG_USERNAME $LOG_PASSWORD

trigger:
  branch:
    - master
    - stable-*
  event:
    - push
    - pull_request
