name: "Assemble"

on:
    pull_request:
        branches: [ master, stable-* ]

jobs:
    flavor:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                java_version: [ 8, 11 ]
                flavor: [ Generic, Gplay ]
        steps:
            -   uses: actions/checkout@v2
            -   name: set up JDK ${{ matrix.java_version }}
                uses: actions/setup-java@v2
                with:
                    distribution: "adopt"
                    java-version: ${{ matrix.java_version }}
            -   name: Build ${{ matrix.flavor }}
                run: |
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties
                    ./gradlew assemble${{ matrix.flavor }}
